authors:
  DR:
    name: Prof. Davide Riboli        # Author name
    description: Cattedra di Applicazioni Digitali per l'Arte # Author description
    avatar: https://codex.accademiasironi.it/assets/logo.png         # Author avatar